2025-07-07 15:34:38,001 p=4425 u=root n=ansible WARNING| [WARNING]: No python interpreters found for host 192.168.56.131 (tried ['python3.13', 'python3.12', 'python3.11', 'python3.10',
'python3.9', 'python3.8', '/usr/bin/python3', 'python3'])

2025-07-07 15:34:38,001 p=4425 u=root n=ansible INFO| 192.168.56.131 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "module_stderr": "Shared connection to 192.168.56.131 closed.\r\n",
    "module_stdout": "/bin/sh: /usr/bin/python3: No such file or directory\r\n",
    "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error",
    "rc": 127
}
2025-07-07 15:34:38,189 p=4425 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python interpreter at /usr/bin/python3, but future
installation of another Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-07 15:34:38,189 p=4425 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
ok

2025-07-07 15:41:52,628 p=4536 u=root n=ansible WARNING| [WARNING]: No python interpreters found for host 192.168.56.131 (tried ['python3.13', 'python3.12', 'python3.11', 'python3.10',
'python3.9', 'python3.8', '/usr/bin/python3', 'python3'])

2025-07-07 15:41:52,628 p=4536 u=root n=ansible INFO| 192.168.56.131 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "module_stderr": "Shared connection to 192.168.56.131 closed.\r\n",
    "module_stdout": "/bin/sh: /usr/bin/python3: No such file or directory\r\n",
    "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error",
    "rc": 127
}
2025-07-07 15:41:52,860 p=4536 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python interpreter at /usr/bin/python3, but future
installation of another Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-07 15:41:52,860 p=4536 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
ok

2025-07-09 10:06:17,850 p=4411 u=root n=ansible INFO| PLAY [all] ************************************************************************************************
2025-07-09 10:06:17,858 p=4411 u=root n=ansible INFO| TASK [test_ansible_runner] ********************************************************************************
2025-07-09 10:06:18,425 p=4411 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python interpreter at
/usr/bin/python3, but future installation of another Python interpreter could change the meaning of that
path. See https://docs.ansible.com/ansible-core/2.18/reference_appendices/interpreter_discovery.html for
more information.

2025-07-09 10:06:18,425 p=4411 u=root n=ansible INFO| changed: [192.168.56.142]
2025-07-09 10:06:20,901 p=4411 u=root n=ansible INFO| fatal: [192.168.56.131]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.131 port 22: No route to host", "unreachable": true}
2025-07-09 10:06:20,902 p=4411 u=root n=ansible INFO| PLAY RECAP ************************************************************************************************
2025-07-09 10:06:20,902 p=4411 u=root n=ansible INFO| 192.168.56.131             : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2025-07-09 10:06:20,902 p=4411 u=root n=ansible INFO| 192.168.56.142             : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2025-07-11 14:43:22,939 p=6120 u=root n=ansible INFO| host01 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.3 port 22: Connection timed out",
    "unreachable": true
}
2025-07-11 14:43:49,626 p=6132 u=root n=ansible INFO| host01 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.3 port 22: Connection timed out",
    "unreachable": true
}
2025-07-11 14:44:27,243 p=6144 u=root n=ansible INFO| host01 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.3 port 22: Connection timed out",
    "unreachable": true
}
2025-07-11 14:47:33,863 p=6168 u=root n=ansible INFO| host01 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.3 port 22: Connection timed out",
    "unreachable": true
}
2025-07-11 14:49:11,779 p=6192 u=root n=ansible INFO| host01 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.3 port 22: Connection timed out",
    "unreachable": true
}
2025-07-11 14:55:17,325 p=6236 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-11 14:55:17,325 p=6236 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
1.sh
anaconda-ks.cfg
ansible.log
ansible_run
dump.rdb
examples
inventory
project
project1
redis-7.2.0
redis-7.2.0.tar.gz
requirements.txt
share
sudo-1.9.15-1.el7.x86_64.rpm
sudo-1.9.5-2.el7.x86_64.rpm
sudo.sh

2025-07-11 14:55:26,781 p=6236 u=root n=ansible INFO| 192.168.1.13 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.13 port 22: Connection timed out",
    "unreachable": true
}
2025-07-11 15:03:49,192 p=6476 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-11 15:03:49,192 p=6476 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
1.sh
anaconda-ks.cfg
ansible.log
ansible_run
dump.rdb
examples
inventory
project
project1
redis-7.2.0
redis-7.2.0.tar.gz
requirements.txt
share
sudo-1.9.15-1.el7.x86_64.rpm
sudo-1.9.5-2.el7.x86_64.rpm
sudo.sh

2025-07-11 15:03:51,649 p=6476 u=root n=ansible INFO| 192.168.56.140 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.140 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:03:51,661 p=6476 u=root n=ansible INFO| 192.168.56.144 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.144 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:04:25,986 p=6581 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-11 15:04:25,986 p=6581 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
1.sh
anaconda-ks.cfg
ansible.log
ansible_run
dump.rdb
examples
inventory
project
project1
redis-7.2.0
redis-7.2.0.tar.gz
requirements.txt
share
sudo-1.9.15-1.el7.x86_64.rpm
sudo-1.9.5-2.el7.x86_64.rpm
sudo.sh

2025-07-11 15:04:28,569 p=6581 u=root n=ansible INFO| 192.168.56.140 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.140 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:04:28,576 p=6581 u=root n=ansible INFO| 192.168.56.144 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.144 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:04:36,147 p=6684 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-11 15:04:36,147 p=6684 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
1.sh
anaconda-ks.cfg
ansible.log
ansible_run
dump.rdb
examples
inventory
project
project1
redis-7.2.0
redis-7.2.0.tar.gz
requirements.txt
share
sudo-1.9.15-1.el7.x86_64.rpm
sudo-1.9.5-2.el7.x86_64.rpm
sudo.sh

2025-07-11 15:04:38,725 p=6684 u=root n=ansible INFO| 192.168.56.140 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.140 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:04:38,729 p=6684 u=root n=ansible INFO| 192.168.56.144 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.144 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:06:32,992 p=6839 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-11 15:06:32,992 p=6839 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
1.sh
anaconda-ks.cfg
ansible.log
ansible_run
dump.rdb
examples
inventory
project
project1
redis-7.2.0
redis-7.2.0.tar.gz
requirements.txt
share
sudo-1.9.15-1.el7.x86_64.rpm
sudo-1.9.5-2.el7.x86_64.rpm
sudo.sh

2025-07-11 15:06:35,463 p=6839 u=root n=ansible INFO| 192.168.56.140 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.140 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:06:35,471 p=6839 u=root n=ansible INFO| 192.168.56.144 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.144 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:10:18,399 p=7963 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-11 15:10:18,399 p=7963 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
1.sh
anaconda-ks.cfg
ansible.log
ansible_run
dump.rdb
examples
inventory
project
project1
redis-7.2.0
redis-7.2.0.tar.gz
requirements.txt
share
sudo-1.9.15-1.el7.x86_64.rpm
sudo-1.9.5-2.el7.x86_64.rpm
sudo.sh

2025-07-11 15:10:20,977 p=7963 u=root n=ansible INFO| 192.168.56.140 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.140 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:10:20,981 p=7963 u=root n=ansible INFO| 192.168.56.144 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.144 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:12:04,052 p=8095 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-11 15:12:04,052 p=8095 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
1.sh
anaconda-ks.cfg
ansible.log
ansible_run
dump.rdb
examples
inventory
project
project1
redis-7.2.0
redis-7.2.0.tar.gz
requirements.txt
share
sudo-1.9.15-1.el7.x86_64.rpm
sudo-1.9.5-2.el7.x86_64.rpm
sudo.sh

2025-07-11 15:12:06,483 p=8095 u=root n=ansible INFO| 192.168.56.140 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.140 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:12:06,484 p=8095 u=root n=ansible INFO| 192.168.56.144 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.144 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:13:29,828 p=8715 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-11 15:13:29,828 p=8715 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
1.sh
anaconda-ks.cfg
ansible.log
ansible_run
dump.rdb
examples
inventory
project
project1
redis-7.2.0
redis-7.2.0.tar.gz
requirements.txt
share
sudo-1.9.15-1.el7.x86_64.rpm
sudo-1.9.5-2.el7.x86_64.rpm
sudo.sh

2025-07-11 15:13:32,413 p=8715 u=root n=ansible INFO| 192.168.56.140 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.140 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:13:32,417 p=8715 u=root n=ansible INFO| 192.168.56.144 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.144 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:13:44,399 p=8829 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-11 15:13:44,400 p=8829 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
1.sh
anaconda-ks.cfg
ansible.log
ansible_run
dump.rdb
examples
inventory
project
project1
redis-7.2.0
redis-7.2.0.tar.gz
requirements.txt
share
sudo-1.9.15-1.el7.x86_64.rpm
sudo-1.9.5-2.el7.x86_64.rpm
sudo.sh

2025-07-11 15:13:50,494 p=9273 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-11 15:13:50,494 p=9273 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
1.sh
anaconda-ks.cfg
ansible.log
ansible_run
dump.rdb
examples
inventory
project
project1
redis-7.2.0
redis-7.2.0.tar.gz
requirements.txt
share
sudo-1.9.15-1.el7.x86_64.rpm
sudo-1.9.5-2.el7.x86_64.rpm
sudo.sh

2025-07-11 15:13:50,665 p=9275 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-11 15:13:50,665 p=9275 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
1.sh
anaconda-ks.cfg
ansible.log
ansible_run
dump.rdb
examples
inventory
project
project1
redis-7.2.0
redis-7.2.0.tar.gz
requirements.txt
share
sudo-1.9.15-1.el7.x86_64.rpm
sudo-1.9.5-2.el7.x86_64.rpm
sudo.sh

2025-07-11 15:13:50,706 p=9279 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-11 15:13:50,706 p=9279 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
1.sh
anaconda-ks.cfg
ansible.log
ansible_run
dump.rdb
examples
inventory
project
project1
redis-7.2.0
redis-7.2.0.tar.gz
requirements.txt
share
sudo-1.9.15-1.el7.x86_64.rpm
sudo-1.9.5-2.el7.x86_64.rpm
sudo.sh

2025-07-11 15:13:51,443 p=9273 u=root n=ansible INFO| 192.168.56.144 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.144 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:13:51,443 p=9273 u=root n=ansible INFO| 192.168.56.140 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.140 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:13:51,445 p=9275 u=root n=ansible INFO| 192.168.56.144 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.144 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:13:51,445 p=9275 u=root n=ansible INFO| 192.168.56.140 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.140 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:13:51,447 p=9279 u=root n=ansible INFO| 192.168.56.140 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.140 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:13:51,447 p=9279 u=root n=ansible INFO| 192.168.56.144 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.144 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:14:47,406 p=9693 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-11 15:14:47,406 p=9693 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
1.sh
anaconda-ks.cfg
ansible.log
ansible_run
dump.rdb
examples
inventory
project
project1
redis-7.2.0
redis-7.2.0.tar.gz
requirements.txt
share
sudo-1.9.15-1.el7.x86_64.rpm
sudo-1.9.5-2.el7.x86_64.rpm
sudo.sh

2025-07-11 15:14:49,994 p=9693 u=root n=ansible INFO| 192.168.56.140 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.140 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:14:50,002 p=9693 u=root n=ansible INFO| 192.168.56.144 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.144 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:16:57,334 p=9966 u=root n=ansible INFO| 192.168.56.142 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.142 port 33: Connection refused",
    "unreachable": true
}
2025-07-11 15:17:00,347 p=9966 u=root n=ansible INFO| 192.168.56.140 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.140 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:17:00,351 p=9966 u=root n=ansible INFO| 192.168.56.144 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.144 port 22: No route to host",
    "unreachable": true
}
2025-07-14 16:14:32,630 p=6819 u=root n=ansible INFO| 192.168.56.144 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.144 port 22: No route to host",
    "unreachable": true
}
2025-07-14 16:14:57,659 p=6851 u=root n=ansible INFO| 192.168.56.142 | UNREACHABLE! => {
    "changed": false,
    "msg": "Invalid/incorrect password: Permission denied, please try again.\r\nPermission denied, please try again.\r\nPermission denied (publickey,gssapi-keyex,gssapi-with-mic,password).",
    "unreachable": true
}
2025-07-14 16:15:08,299 p=6879 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-14 16:15:08,299 p=6879 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
total 9336
dr-xr-x---. 15 root root    4096 Jul 14 16:10 .
dr-xr-xr-x. 17 root root     270 Jul  4 10:23 ..
-rwxrwxrwx   1 root root     636 Jul  2 17:08 1.sh
-rw-------.  1 root root    1337 Nov 18  2024 anaconda-ks.cfg
drwx------   4 root root      27 Jul  3 16:54 .ansible
-rw-r--r--   1 root root   11101 Jul  3 17:28 ansible.log
drwxr-xr-x   5 root root     153 Jul  4 16:10 ansible_run
-rw-------.  1 root root   20428 Jul 11 17:27 .bash_history
-rw-r--r--.  1 root root      18 Dec 29  2013 .bash_logout
-rw-r--r--.  1 root root     176 Dec 29  2013 .bash_profile
-rw-r--r--   1 root root     190 Nov 18  2024 .bashrc
drwxr-xr-x   3 root root      17 Jul  4 10:52 .cache
drwxr-xr-x   3 root root      23 Jul  4 10:45 .config
-rw-r--r--.  1 root root     100 Dec 29  2013 .cshrc
-rw-r--r--   1 root root    3875 Jul 14 16:10 dump.rdb
drwxr-xr-x   3 root root      17 Jul  3 17:02 examples
-rw-r--r--   1 root root      78 Jul  7 09:33 .gitconfig
-rw-------   1 root root      41 Jul 11 17:26 .git-credentials
drwxr-xr-x   2 root root       6 Jul  4 09:09 inventory
-rw-------   1 root root      45 Jul  7 16:09 .lesshst
drwxr-----   3 root root      19 Jul  4 10:46 .pki
drwxr-xr-x   8 root root     156 Jul  7 10:29 project
drwxr-xr-x   3 root root      35 Dec  3  2024 project1
drwxr-xr-x  22 root root    4096 Jul  4 11:21 .pycharm_helpers
-rw-r--r--   1 root root       7 Jul  4 11:18 .python_history
drwxrwxr-x   8 root root    4096 Jul  8 11:07 redis-7.2.0
-rw-rw-rw-   1 root root 3381269 Aug 15  2023 redis-7.2.0.tar.gz
-rw-r--r--   1 root root     305 Jul  4 11:16 requirements.txt
drwxrwxrwx   2 root root       6 Jul  4 11:12 share
drwx------   2 root root      25 Jul  3 16:56 .ssh
-rw-r--r--   1 root root 3672728 Nov  7  2023 sudo-1.9.15-1.el7.x86_64.rpm
-rw-r--r--   1 root root 2382800 Jan 12  2021 sudo-1.9.5-2.el7.x86_64.rpm
-rw-r--r--   1 root root    2503 Apr 21 15:33 sudo.sh
-rw-r--r--.  1 root root     129 Dec 29  2013 .tcshrc
-rw-------   1 root root    8763 Jul 11 15:10 .viminfo
-rw-r--r--   1 root root      10 Nov 18  2024 .vimrc

2025-07-14 16:38:42,255 p=7114 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-14 16:38:42,255 p=7114 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
total 9352
dr-xr-x---. 15 root root    4096 Jul 14 16:15 .
dr-xr-xr-x. 17 root root     270 Jul  4 10:23 ..
-rwxrwxrwx   1 root root     636 Jul  2 17:08 1.sh
-rw-------.  1 root root    1337 Nov 18  2024 anaconda-ks.cfg
drwx------   4 root root      27 Jul  3 16:54 .ansible
-rw-r--r--   1 root root   11101 Jul  3 17:28 ansible.log
drwxr-xr-x   5 root root     153 Jul  4 16:10 ansible_run
-rw-------.  1 root root   20428 Jul 11 17:27 .bash_history
-rw-r--r--.  1 root root      18 Dec 29  2013 .bash_logout
-rw-r--r--.  1 root root     176 Dec 29  2013 .bash_profile
-rw-r--r--   1 root root     190 Nov 18  2024 .bashrc
drwxr-xr-x   3 root root      17 Jul  4 10:52 .cache
drwxr-xr-x   3 root root      23 Jul  4 10:45 .config
-rw-r--r--.  1 root root     100 Dec 29  2013 .cshrc
-rw-r--r--   1 root root   16553 Jul 14 16:15 dump.rdb
drwxr-xr-x   3 root root      17 Jul  3 17:02 examples
-rw-r--r--   1 root root      78 Jul  7 09:33 .gitconfig
-rw-------   1 root root      41 Jul 14 16:15 .git-credentials
drwxr-xr-x   2 root root       6 Jul  4 09:09 inventory
-rw-------   1 root root      45 Jul  7 16:09 .lesshst
drwxr-----   3 root root      19 Jul  4 10:46 .pki
drwxr-xr-x   8 root root     156 Jul  7 10:29 project
drwxr-xr-x   3 root root      35 Dec  3  2024 project1
drwxr-xr-x  22 root root    4096 Jul  4 11:21 .pycharm_helpers
-rw-r--r--   1 root root       7 Jul  4 11:18 .python_history
drwxrwxr-x   8 root root    4096 Jul  8 11:07 redis-7.2.0
-rw-rw-rw-   1 root root 3381269 Aug 15  2023 redis-7.2.0.tar.gz
-rw-r--r--   1 root root     305 Jul  4 11:16 requirements.txt
drwxrwxrwx   2 root root       6 Jul  4 11:12 share
drwx------   2 root root      25 Jul  3 16:56 .ssh
-rw-r--r--   1 root root 3672728 Nov  7  2023 sudo-1.9.15-1.el7.x86_64.rpm
-rw-r--r--   1 root root 2382800 Jan 12  2021 sudo-1.9.5-2.el7.x86_64.rpm
-rw-r--r--   1 root root    2503 Apr 21 15:33 sudo.sh
-rw-r--r--.  1 root root     129 Dec 29  2013 .tcshrc
-rw-------   1 root root    8763 Jul 11 15:10 .viminfo
-rw-r--r--   1 root root      10 Nov 18  2024 .vimrc

2025-07-15 13:28:31,557 p=12116 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-15 13:28:31,558 p=12116 u=root n=ansible INFO| 192.168.56.142 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2025-07-15 13:28:34,032 p=12116 u=root n=ansible INFO| 192.168.56.144 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.144 port 22: No route to host",
    "unreachable": true
}
